config/routes.rb
PowerBridge::Application.routes.draw do
  
  
  resources :customers do
    resources :devices
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :goNum, :name, :status, :deviceCount
  
   # attr_accessible :alternate_dns_server, :amps, :customer_id, :default_gateway, :descName, :desc_bucket, :desc_location, :device_type, :domain_name, :ds_name, :firmware, :frame_size, :host_name, :incom_address, :ip_address_setting, :lan_type, :mac_address, :modbus_tcp_enabled, :name, :plug_ctrating, :power_factor, :preferred_dns_server, :status, :subnet_mask, :trending, :upstream_device, :voltage_class
  
  has_many :devices
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :alternate_dns_server, :amps, :customer_id, :default_gateway, :descName, :desc_bucket, :desc_location, :device_type, :domain_name, :ds_name, :firmware, :frame_size, :host_name, :incom_address, :ip_address_setting, :lan_type, :mac_address, :modbus_tcp_enabled, :name, :plug_ctrating, :power_factor, :preferred_dns_server, :status, :subnet_mask, :trending, :upstream_device, :voltage_class, :created_at

  belongs_to :customer
  
  def realStatus
    if self.status == 0
      self.status = "Not found"
    elsif self.status == 1
      self.status = "Detected"
    elsif self.status == 2
      self.status = "Complete"
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  skip_before_filter  :verify_authenticity_token
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  skip_before_filter  :verify_authenticity_token
  
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, :notice => 'Customer was successfully created.' }
        format.json { render :json => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, :notice => 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  
  # skip_before_filter :verify_authenticity_token, :except => [:update, :create]
  #   skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  skip_before_filter  :verify_authenticity_token
  
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @customer = Customer.find(params[:customer_id])
    @device = @customer.devices.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @customer = Customer.find(params[:customer_id])
    @device = @customer.devices.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @customer = Customer.find(params[:customer_id])
    @device = @customer.devices.new(params[:device])

    respond_to do |format|
      if @device.save
        format.html { redirect_to([@customer,@device], :notice => 'Device was successfully updated.') }
        format.json { render :json => @device, :status => :created, :location => @device }
      else
        format.html { render :action => "new" }
        format.json { render :json => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @customer = Customer.find(params[:customer_id])
    @device = @customer.devices.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to([@customer,@device], :notice => 'Device was successfully updated.') }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @device.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(customer_path(@device.customer_id)) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :goNum, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :goNum, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :deviceCount, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :deviceCount, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<%- model_class = @customer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/index.html.erb
<%- model_class = Customer.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:goNum) %></th>
      <th><%= model_class.human_attribute_name(:deviceCount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer_path(customer) %></td>
        <td><%= customer.status %></td>
        <td><%= customer.goNum %></td>
        <td><%= customer.deviceCount %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<%- model_class = @customer.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<%- model_class = @customer.class -%>
<div class="page-header">
  <h1><%=@customer.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @customer.status %></dd>
  <dt><strong>Order Number:</strong></dt>
  <dd><%= @customer.goNum %></dd>
  <dt><strong>Device Count:</strong></dt>
  <dd><%= @customer.deviceCount %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_path(@customer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_path(@customer),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
<p id="pdf_link"><%= link_to "Client Report", customer_path(@customer, :format => "pdf"), :class => 'btn' %></p>
</div>

<h1>Devices</h1>
<table class="table table-striped">
  <thead>
    <tr>
		<th></th>
      	<th>Device Name</th>
		<th>Device Type</th>
		<th>Address</th>
		<th>Compartment Number</th>
		<th>Upstream Device</th>
		<th>MAC Address</th>
		<th>Firmware Revision</th>
		<th>LAN Type</th>
		<th>Domain Name</th>
		<th>Modbus TCP Enabled</th>
		<th>Amps</th>
		<th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @customer.devices.each do |device| %>
      <tr>
		<td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_device_path(device.customer_id, device), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_device_path(device.customer_id, device),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
		</td>
         <td><%= link_to device.desc_location, customer_device_path(device.customer_id, device) %></td>
		<td><%= device.device_type %></td>
		<td><%= device.incom_address %></td>
		<td><%= device.desc_bucket %></td>
		<td><%= device.upstream_device %></td>
		<td><%= device.mac_address %></td>
		<td><%= device.firmware %></td>
		<td><%= device.lan_type %></td>
		<td><%= device.domain_name %></td>
		<td><%= device.modbus_tcp_enabled %></td>
		<td><%= device.amps %></td>
		<td><%= device.realStatus %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_device_path(@customer),
            :class => 'btn btn-primary' %>

app/views/devices/_form.html.erb
<%= form_for [@customer, @device] do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :incom_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :incom_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :device_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :device_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ds_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ds_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :frame_size, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :frame_size, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descName, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descName, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc_location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc_location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc_bucket, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc_bucket, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :trending, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :trending, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :plug_ctrating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :plug_ctrating, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :voltage_class, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :voltage_class, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :status, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :upstream_device, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :upstream_device, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mac_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mac_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :firmware, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firmware, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :amps, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amps, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :power_factor, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :power_factor, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :lan_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lan_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :host_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :host_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ip_address_setting, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ip_address_setting, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subnet_mask, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subnet_mask, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :default_gateway, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :default_gateway, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :preferred_dns_server, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :preferred_dns_server, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :alternate_dns_server, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :alternate_dns_server, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :domain_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :domain_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :modbus_tcp_enabled, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :modbus_tcp_enabled, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_path(@customer), :class => 'btn' %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<%- model_class = @device.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      	<th>Device Name</th>
		<th>Device Type</th>
		<th>Address</th>
		<th>Compartment Number</th>
		<th>Upstream Device</th>
		<th>MAC Address</th>
		<th>Firmware Revision</th>
		<th>LAN Type</th>
		<th>Host Name</th>
		<th>Subnet Mask</th>
		<th>IP Address Setting</th>
		<th>Preferred DNS Server</th>
		<th>Alternate DNS Server</th>
		<th>Domain Name</th>
		<th>Modbus TCP Enabled</th>
		<th>Amps</th>
		<th>Power Factor</th>
		<th>Status</th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= link_to device.desc_location, device_path(device.customer_id, device) %></td>
		<td><%= device.device_type %></td>
		<td><%= device.incom_address %></td>
		<td><%= device.desc_bucket %></td>
		<td><%= device.upstream_device %></td>
		<td><%= device.mac_address %></td>
		<td><%= device.firmware %></td>
		<td><%= device.lan_type %></td>
		<td><%= device.host_name %></td>
		<td><%= device.subnet_mask %></td>
		<td><%= device.ip_address_setting %></td>
		<td><%= device.default_gateway %></td>
		<td><%= device.preferred_dns_server %></td>
		<td><%= device.alternate_dns_server %></td>
		<td><%= device.domain_name %></td>
		<td><%= device.modbus_tcp_ip_enabled %></td>
		<td><%= device.amps %></td>
		<td><%= device.realStatus %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_device_path(device), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      device_path(device),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_device_path,
            :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<%- model_class = @device.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/devices/show.html.erb
<%- model_class = @device.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:incom_address) %>:</strong></dt>
  <dd><%= @device.incom_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:device_type) %>:</strong></dt>
  <dd><%= @device.device_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ds_name) %>:</strong></dt>
  <dd><%= @device.ds_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:frame_size) %>:</strong></dt>
  <dd><%= @device.frame_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descName) %>:</strong></dt>
  <dd><%= @device.descName %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc_location) %>:</strong></dt>
  <dd><%= @device.desc_location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc_bucket) %>:</strong></dt>
  <dd><%= @device.desc_bucket %></dd>
  <dt><strong><%= model_class.human_attribute_name(:trending) %>:</strong></dt>
  <dd><%= @device.trending %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plug_ctrating) %>:</strong></dt>
  <dd><%= @device.plug_ctrating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:voltage_class) %>:</strong></dt>
  <dd><%= @device.voltage_class %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @device.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:upstream_device) %>:</strong></dt>
  <dd><%= @device.upstream_device %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mac_address) %>:</strong></dt>
  <dd><%= @device.mac_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firmware) %>:</strong></dt>
  <dd><%= @device.firmware %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amps) %>:</strong></dt>
  <dd><%= @device.amps %></dd>
  <dt><strong><%= model_class.human_attribute_name(:power_factor) %>:</strong></dt>
  <dd><%= @device.power_factor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lan_type) %>:</strong></dt>
  <dd><%= @device.lan_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:host_name) %>:</strong></dt>
  <dd><%= @device.host_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ip_address_setting) %>:</strong></dt>
  <dd><%= @device.ip_address_setting %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subnet_mask) %>:</strong></dt>
  <dd><%= @device.subnet_mask %></dd>
  <dt><strong><%= model_class.human_attribute_name(:default_gateway) %>:</strong></dt>
  <dd><%= @device.default_gateway %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preferred_dns_server) %>:</strong></dt>
  <dd><%= @device.preferred_dns_server %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alternate_dns_server) %>:</strong></dt>
  <dd><%= @device.alternate_dns_server %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domain_name) %>:</strong></dt>
  <dd><%= @device.domain_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modbus_tcp_enabled) %>:</strong></dt>
  <dd><%= @device.modbus_tcp_enabled %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customer_path(@device.customer_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_device_path(@device.customer_id, @device), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_device_path(@device),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PowerBridge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" style="font-family:helvetica; text-shadow:0 -1px 1px #333; color:white;" href="#"><span style="font-weight:normal;">Power</span><span style="font-weight:bold;">BRIDGE</span></a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Manuals" %></li>
            <li><%= link_to "iOS" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
    </div>
  </div>
</body>
</html>